name: check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.2
          - 27.1
          - 26.1
          - 26.2
          - 26.3
        ignore_warnings:
          - false
    steps:
    - uses: actions/checkout@v2
    - name: Install just
      shell: bash
      run: |
        set -ex
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin/just
        echo $PATH
        just --version
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        file: '*.el'
        check: melpa
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: true
    - name: ERT tests
      uses: leotaku/elisp-check@master
      with:
        file: '*.el'
        check: ert
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: true
